services:
  - type: web
    name: astraplay-cinema
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: PORT
        value: 10000
