export interface PublicDomainMovie {
  id: string;
  type: "movie";
  name: string;
  year: number;
  releaseInfo: string;
  imdbRating: string;
  genres: string[];
  description: string;
  runtime: string;
  poster: string;
  background: string;
  streamUrl: string;
}

export const PUBLIC_DOMAIN_MOVIES: PublicDomainMovie[] = [
  {
    id: "pd_night_of_the_living_dead_1968",
    type: "movie",
    name: "Night of the Living Dead",
    year: 1968,
    releaseInfo: "1968",
    imdbRating: "7.8",
    genres: ["Horror", "Thriller", "Public Domain"],
    description: "A ragtag group of Pennsylvanians barricade themselves in an old farmhouse to remain safe from a bloodthirsty, flesh-eating breed of reanimated ghouls. Directed by George A. Romero.",
    runtime: "1h 36m",
    poster: "https://images.metahub.space/poster/medium/tt0063350/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0063350/img.jpg",
    streamUrl: "https://archive.org/download/night_of_the_living_dead/night_of_the_living_dead_512kb.mp4",
  },
  {
    id: "pd_charade_1963",
    type: "movie",
    name: "Charade",
    year: 1963,
    releaseInfo: "1963",
    imdbRating: "7.9",
    genres: ["Mystery", "Comedy", "Romance", "Public Domain"],
    description: "A woman is pursued by several men who want a fortune her murdered husband had stolen. Whom can she trust? Starring Cary Grant and Audrey Hepburn.",
    runtime: "1h 53m",
    poster: "https://images.metahub.space/poster/medium/tt0056923/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0056923/img.jpg",
    streamUrl: "https://archive.org/download/Charade1963/Charade1963.mp4",
  },
  {
    id: "pd_his_girl_friday_1940",
    type: "movie",
    name: "His Girl Friday",
    year: 1940,
    releaseInfo: "1940",
    imdbRating: "7.8",
    genres: ["Comedy", "Romance", "Drama", "Public Domain"],
    description: "A newspaper editor uses every trick in the book to keep his ace reporter ex-wife from remarrying and quitting journalism. Directed by Howard Hawks.",
    runtime: "1h 32m",
    poster: "https://images.metahub.space/poster/medium/tt0032599/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0032599/img.jpg",
    streamUrl: "https://archive.org/download/HisGirlFriday1940_201708/His_Girl_Friday_1940.mp4",
  },
  {
    id: "pd_the_general_1926",
    type: "movie",
    name: "The General",
    year: 1926,
    releaseInfo: "1926",
    imdbRating: "8.1",
    genres: ["Action", "Adventure", "Comedy", "Public Domain"],
    description: "During the American Civil War, a Southern railway engineer is rejected by the Confederate army but gets the chance to prove his bravery when Union spies hijack his beloved locomotive.",
    runtime: "1h 18m",
    poster: "https://images.metahub.space/poster/medium/tt0017925/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0017925/img.jpg",
    streamUrl: "https://archive.org/download/TheGeneralBusterKeaton1926/TheGeneralBusterKeaton1926.mp4",
  },
  {
    id: "pd_nosferatu_1922",
    type: "movie",
    name: "Nosferatu",
    year: 1922,
    releaseInfo: "1922",
    imdbRating: "7.9",
    genres: ["Horror", "Fantasy", "Public Domain"],
    description: "Vampire Count Orlok expresses interest in a new residence and real estate agent Hutter's wife. F.W. Murnau's legendary German expressionist silent horror masterpiece.",
    runtime: "1h 34m",
    poster: "https://images.metahub.space/poster/medium/tt0013442/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0013442/img.jpg",
    streamUrl: "https://archive.org/download/Nosferatu_1922_BFI/Nosferatu_1922_BFI_512kb.mp4",
  },
  {
    id: "pd_carnival_of_souls_1962",
    type: "movie",
    name: "Carnival of Souls",
    year: 1962,
    releaseInfo: "1962",
    imdbRating: "7.1",
    genres: ["Horror", "Mystery", "Public Domain"],
    description: "After a traumatic drag-racing accident, a church organist finds herself inexplicably drawn to an abandoned lakeside pavilion and haunted by a mysterious ghoul.",
    runtime: "1h 18m",
    poster: "https://images.metahub.space/poster/medium/tt0055830/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0055830/img.jpg",
    streamUrl: "https://archive.org/download/carnival_of_souls/carnival_of_souls_512kb.mp4",
  },
  {
    id: "pd_house_on_haunted_hill_1959",
    type: "movie",
    name: "House on Haunted Hill",
    year: 1959,
    releaseInfo: "1959",
    imdbRating: "6.8",
    genres: ["Horror", "Mystery", "Public Domain"],
    description: "An eccentric millionaire offers $10,000 to five guests who agree to be locked in a terrifying haunted mansion overnight. Starring Vincent Price.",
    runtime: "1h 15m",
    poster: "https://images.metahub.space/poster/medium/tt0051744/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0051744/img.jpg",
    streamUrl: "https://archive.org/download/house_on_haunted_hill/house_on_haunted_hill_512kb.mp4",
  },
  {
    id: "pd_plan_9_1959",
    type: "movie",
    name: "Plan 9 from Outer Space",
    year: 1959,
    releaseInfo: "1959",
    imdbRating: "4.0",
    genres: ["Sci-Fi", "Horror", "Cult Classic", "Public Domain"],
    description: "Aliens enact 'Plan 9', resuscitating the dead of Earth to stop humanity from creating a doomsday weapon. Ed Wood's infamous cult science fiction film.",
    runtime: "1h 19m",
    poster: "https://images.metahub.space/poster/medium/tt0052077/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0052077/img.jpg",
    streamUrl: "https://archive.org/download/Plan_9_from_Outer_Space_1959/Plan_9_from_Outer_Space_1959_512kb.mp4",
  },
  {
    id: "pd_phantom_opera_1925",
    type: "movie",
    name: "The Phantom of the Opera",
    year: 1925,
    releaseInfo: "1925",
    imdbRating: "7.5",
    genres: ["Horror", "Drama", "Public Domain"],
    description: "A mad, disfigured composer seeks love with a lovely young opera singer in Paris. Lon Chaney stars as the legendary Phantom.",
    runtime: "1h 33m",
    poster: "https://images.metahub.space/poster/medium/tt0016220/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0016220/img.jpg",
    streamUrl: "https://archive.org/download/the-phantom-of-the-opera-1925/the-phantom-of-the-opera-1925.mp4",
  },
  {
    id: "pd_metropolis_1927",
    type: "movie",
    name: "Metropolis",
    year: 1927,
    releaseInfo: "1927",
    imdbRating: "8.3",
    genres: ["Sci-Fi", "Drama", "Public Domain"],
    description: "In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a working-class prophet. Fritz Lang's sci-fi monument.",
    runtime: "2h 33m",
    poster: "https://images.metahub.space/poster/medium/tt0017136/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0017136/img.jpg",
    streamUrl: "https://archive.org/download/Metropolis_1927_Remastered/Metropolis_1927_Remastered.mp4",
  },
  {
    id: "pd_caligari_1920",
    type: "movie",
    name: "The Cabinet of Dr. Caligari",
    year: 1920,
    releaseInfo: "1920",
    imdbRating: "8.0",
    genres: ["Horror", "Mystery", "Thriller", "Public Domain"],
    description: "Hypnotist Dr. Caligari uses a somnambulist to commit murders in a small mountain town. The landmark triumph of German Expressionist filmmaking.",
    runtime: "1h 17m",
    poster: "https://images.metahub.space/poster/medium/tt0010323/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0010323/img.jpg",
    streamUrl: "https://archive.org/download/DasCabinettDesDr.Caligari/Das_Cabinet_des_Dr._Caligari.mp4",
  },
  {
    id: "pd_doa_1949",
    type: "movie",
    name: "D.O.A.",
    year: 1949,
    releaseInfo: "1949",
    imdbRating: "7.3",
    genres: ["Film-Noir", "Crime", "Mystery", "Public Domain"],
    description: "Frank Bigelow, told he has been poisoned and has only a few days to live, frantically searches for who murdered him and why. Classic noir thriller.",
    runtime: "1h 23m",
    poster: "https://images.metahub.space/poster/medium/tt0042369/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0042369/img.jpg",
    streamUrl: "https://archive.org/download/DOA1950/DOA1950_512kb.mp4",
  },
  {
    id: "pd_little_shop_1960",
    type: "movie",
    name: "The Little Shop of Horrors",
    year: 1960,
    releaseInfo: "1960",
    imdbRating: "6.2",
    genres: ["Comedy", "Horror", "Public Domain"],
    description: "A clumsy young man working in a Skid Row flower shop discovers that an exotic plant he cultivated has an appetite for human blood. Roger Corman cult classic.",
    runtime: "1h 12m",
    poster: "https://images.metahub.space/poster/medium/tt0054033/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0054033/img.jpg",
    streamUrl: "https://archive.org/download/the-little-shop-of-horrors-1960/The_Little_Shop_of_Horrors_1960.mp4",
  },
  {
    id: "pd_last_man_earth_1964",
    type: "movie",
    name: "The Last Man on Earth",
    year: 1964,
    releaseInfo: "1964",
    imdbRating: "6.8",
    genres: ["Horror", "Sci-Fi", "Public Domain"],
    description: "Dr. Robert Morgan is the only human survivor of a global plague that has turned humanity into bloodthirsty vampiric mutants. Starring Vincent Price.",
    runtime: "1h 26m",
    poster: "https://images.metahub.space/poster/medium/tt0058281/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0058281/img.jpg",
    streamUrl: "https://archive.org/download/TheLastManOnEarth_762/The_Last_Man_on_Earth.mp4",
  },
  {
    id: "pd_the_stranger_1946",
    type: "movie",
    name: "The Stranger",
    year: 1946,
    releaseInfo: "1946",
    imdbRating: "7.3",
    genres: ["Crime", "Film-Noir", "Thriller", "Public Domain"],
    description: "An investigator from the War Crimes Commission travels to Connecticut to find an escaped Nazi mastermind living under an assumed identity. Directed by and starring Orson Welles.",
    runtime: "1h 35m",
    poster: "https://images.metahub.space/poster/medium/tt0038991/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0038991/img.jpg",
    streamUrl: "https://archive.org/download/TheStranger1946OrsonWelles/The_Stranger_1946.mp4",
  },
  {
    id: "pd_detour_1945",
    type: "movie",
    name: "Detour",
    year: 1945,
    releaseInfo: "1945",
    imdbRating: "7.3",
    genres: ["Crime", "Drama", "Film-Noir", "Public Domain"],
    description: "A down-on-his-luck nightclub pianist hitchhiking across the country is ensnared in a web of accidental death and blackmail. Edgar G. Ulmer's definitive B-noir.",
    runtime: "1h 08m",
    poster: "https://images.metahub.space/poster/medium/tt0037638/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0037638/img.jpg",
    streamUrl: "https://archive.org/download/Detour_1945/Detour_1945_512kb.mp4",
  },
  {
    id: "pd_white_zombie_1932",
    type: "movie",
    name: "White Zombie",
    year: 1932,
    releaseInfo: "1932",
    imdbRating: "6.3",
    genres: ["Horror", "Public Domain"],
    description: "A young couple in Haiti encounters a sinister plantation owner who uses voodoo to transform the living into mindless laborers. Starring Bela Lugosi.",
    runtime: "1h 09m",
    poster: "https://images.metahub.space/poster/medium/tt0023694/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0023694/img.jpg",
    streamUrl: "https://archive.org/download/WhiteZombie1932/White_Zombie_1932.mp4",
  },
  {
    id: "open_big_buck_bunny_2008",
    type: "movie",
    name: "Big Buck Bunny",
    year: 2008,
    releaseInfo: "2008",
    imdbRating: "7.0",
    genres: ["Animation", "Comedy", "Open Film"],
    description: "A giant rabbit with a heart bigger than himself resolves to get even with three bullying forest critters. Blender Open Movie Foundation open-source cinema.",
    runtime: "10m",
    poster: "https://images.metahub.space/poster/medium/tt1254207/img.jpg",
    background: "https://images.metahub.space/background/medium/tt1254207/img.jpg",
    streamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  },
  {
    id: "open_sintel_2010",
    type: "movie",
    name: "Sintel",
    year: 2010,
    releaseInfo: "2010",
    imdbRating: "7.4",
    genres: ["Animation", "Fantasy", "Open Film"],
    description: "A lonely young woman searches the far ends of the earth to rescue a wounded dragon scale companion she befriended. Blender Open Movie Project.",
    runtime: "15m",
    poster: "https://images.metahub.space/poster/medium/tt1727587/img.jpg",
    background: "https://images.metahub.space/background/medium/tt1727587/img.jpg",
    streamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  },
  {
    id: "open_tears_of_steel_2012",
    type: "movie",
    name: "Tears of Steel",
    year: 2012,
    releaseInfo: "2012",
    imdbRating: "5.5",
    genres: ["Sci-Fi", "Action", "Open Film"],
    description: "In a dystopian future, a group of scientists and warriors in Amsterdam attempt to rescue a post-apocalyptic world from robotic domination using VFX. Blender Open Movie.",
    runtime: "12m",
    poster: "https://images.metahub.space/poster/medium/tt2285752/img.jpg",
    background: "https://images.metahub.space/background/medium/tt2285752/img.jpg",
    streamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  },
  {
    id: "open_elephants_dream_2006",
    type: "movie",
    name: "Elephants Dream",
    year: 2006,
    releaseInfo: "2006",
    imdbRating: "6.8",
    genres: ["Animation", "Sci-Fi", "Open Film"],
    description: "Two strange travelers explore the complex mechanical conduits of a mysterious and infinite computational labyrinth. The world's first open-movie project.",
    runtime: "11m",
    poster: "https://images.metahub.space/poster/medium/tt0816436/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0816436/img.jpg",
    streamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  },
  {
    id: "pd_gullivers_travels_1939",
    type: "movie",
    name: "Gulliver's Travels",
    year: 1939,
    releaseInfo: "1939",
    imdbRating: "6.7",
    genres: ["Animation", "Adventure", "Family", "Public Domain"],
    description: "Lemuel Gulliver washes ashore on the island of Lilliput after a shipwreck, helping prevent a war between rival tiny kingdoms. Max Fleischer classic animation.",
    runtime: "1h 16m",
    poster: "https://images.metahub.space/poster/medium/tt0031397/img.jpg",
    background: "https://images.metahub.space/background/medium/tt0031397/img.jpg",
    streamUrl: "https://archive.org/download/GulliversTravels1939_201602/Gullivers_Travels_1939.mp4",
  },
];

export const PUBLIC_DOMAIN_MANIFEST = {
  id: "org.astraplay.publicdomain",
  name: "Public Domain & Open Cinema",
  version: "2.0.0",
  description: "Verified genuine public domain classics, open-source cinema (Blender Open Projects), and Internet Archive films.",
  resources: ["catalog", "meta", "stream"],
  types: ["movie"],
  catalogs: [
    {
      type: "movie",
      id: "public_domain",
      name: "Public Domain Feature Films",
      extra: [{ name: "search", isRequired: false }, { name: "skip", isRequired: false }],
    },
  ],
};

export function getPublicDomainMetas(skip = 0, query?: string) {
  let list = PUBLIC_DOMAIN_MOVIES;
  if (query && query.trim()) {
    const q = query.toLowerCase().trim();
    list = list.filter(
      (m) =>
        m.name.toLowerCase().includes(q) ||
        m.description.toLowerCase().includes(q) ||
        m.genres.some((g) => g.toLowerCase().includes(q))
    );
  }
  return list.slice(skip, skip + 30).map((m) => ({
    id: m.id,
    type: m.type,
    name: m.name,
    year: m.year,
    releaseInfo: m.releaseInfo,
    imdbRating: m.imdbRating,
    genres: m.genres,
    description: m.description,
    runtime: m.runtime,
    poster: m.poster,
    background: m.background,
  }));
}

export function getPublicDomainMeta(id: string) {
  const found = PUBLIC_DOMAIN_MOVIES.find((m) => m.id === id);
  if (!found) return null;
  return {
    id: found.id,
    type: found.type,
    name: found.name,
    year: found.year,
    releaseInfo: found.releaseInfo,
    imdbRating: found.imdbRating,
    genres: found.genres,
    description: found.description,
    runtime: found.runtime,
    poster: found.poster,
    background: found.background,
  };
}

export function getPublicDomainStreams(id: string) {
  const found = PUBLIC_DOMAIN_MOVIES.find((m) => m.id === id);
  if (!found) return [];
  return [
    {
      name: "Public Domain Archive",
      title: `${found.name} (Direct Stream)`,
      url: found.streamUrl,
      quality: "1080p",
      addonName: "Public Domain & Open Cinema",
    },
  ];
}
